### ISSUE TITLE
Error inflating class com.synnapps.carouselview.CarouselView

### ISSUE THREAD

**Issue by MasterzYuri** [sayyam/carouselview#14]
I have implemented this library in my app, I tested it using Device Emulator and a real device (Galaxy S5), everything was working well so I updated my app. After a few hours I downloaded my app from Play Store and I noticed that it crashes when I open the activity containing the carouselview.

Crash report:
```
java.lang.RuntimeException: Unable to start activity MncDetails{com.mypackage}: android.view.InflateException: Binary XML file line #35: Error inflating class com.synnapps.carouselview.CarouselView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2449)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509)
	at android.app.ActivityThread.access$900(ActivityThread.java:172)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5694)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: android.view.InflateException: Binary XML file line #35: Error inflating class com.synnapps.carouselview.CarouselView
...
```
I added this line `-keep class com.synnapps:carouselview.** { *; }` to **proguard-rules.pro** but I'm still getting that error.

**Comment by sayyam** [comment]
Can you please provide a sample app to reproduce this crash?

**Comment by MasterzYuri** [comment]
Sure, but I'm not sure how that's gonna help because, for some reason, the error only shows if the app is published in Play Store. It happend to me before when I used MaterialDrawer ( by Mike Penz ), I remember that I solved the issue by adding a line in proguard.

**Comment by MasterzYuri** [comment]
[http://www.filedropper.com/carouseltest](url)

**Comment by sayyam** [comment]
Package name is invalid in progaurd entry.

Please try replacing `-keep class com.synnapps:carouselview.** { *; }` 
with `-keep class com.synnapps.carouselview.** { *; }` in your **proguard-rules.pro**.

**Comment by MasterzYuri** [comment]
I'm still getting the error. I will try again when I get back from school.

**Comment by MasterzYuri** [comment]
Solved!
Solution: `-keep class com.synnapps.carouselview.** { *; }` 
Thank you and sorry for my late reply ^_^

**Comment by Fargren** [comment]
This should probably be added to the readme
