### ISSUE TITLE
Carousel View requires FrameLayout has parent

### ISSUE THREAD

**Issue by dsuresh-ap** [sayyam/carouselview#65]
When calling setIndicatorMarginVertical() it crashes with the following exception. It does not happen when setting the indicator margin attributes in the layout file.

Caused by: java.lang.ClassCastException: android.widget.RelativeLayout$LayoutParams cannot be cast to android.widget.FrameLayout$LayoutParams
at com.synnapps.carouselview.CarouselView.setIndicatorMarginVertical(CarouselView.java:450)

**Comment by ajhuntsman** [comment]
Here's the stack trace when using version 0.1.4:
`java.lang.ClassCastException: android.widget.RelativeLayout$LayoutParams cannot be cast to android.widget.FrameLayout$LayoutParams at com.synnapps.carouselview.CarouselView.setIndicatorMarginVertical(CarouselView.java:456)`
